### ISSUE TITLE
Webhooks getting queued when "Use system value" is checked

### ISSUE THREAD

**Issue by indykoning** [mageplaza/magento-2-webhook#23]
When you freshly install this module, save the config without any changes.
Thus keeping "Schedule For Cron" on "Disable" and "Use system value" checked
It does not save a value in "core_config_data".

This results in https://github.com/mageplaza/magento-2-webhook/blob/master/Helper/Data.php#L508
returning `null` causing [these checks](https://github.com/mageplaza/magento-2-webhook/blob/master/Observer/Subscriber.php#L49) to fail since `null !== '0'` results in `true` causing the webhooks to be queued without ever getting executed.

One proposed solution would be returning `'0'` if the `schedule for cron` option returns `null`
Or removing the "Use system value" checkbox.

**Comment by thaimageplaza** [comment]
Hi Indykoning!
Thank you for contacting us.


your issue has been fixed in extension develop branch.
I have also attached the file in this comment to fix the problem.
The path of the file is:
Mageplaza/Webhook/etc/config.xml
[config.zip](https://github.com/mageplaza/magento-2-webhook/files/4051895/config.zip)
You can replace it to solve the issue or wait. We will release them soon!

Have a nice day!

**Comment by indykoning** [comment]
Thank you,
i can wait for the next release since it's easy enough to fix by unchecking the "Use system value" option.
I am happy to hear that it has already been taken care of.
