### ISSUE TITLE
Problem with some webhooks (not fired) .

### ISSUE THREAD

**Issue by icychocolate98** [mageplaza/magento-2-webhook#36]
I have a problem with the following webhooks:
```
- new login
- update customer
- new subscriber.
```
I suppose that new login is fired when a customer logs in; update customer when customer updates something in his/her profile and new subscriber when any customer subscribes newsletter; am I right?

I realized that webhook are not fired, should I change something internally or do you have other idea?

Thank you!

**Comment by Shinichi69** [comment]
Hi @icychocolate98 

The updated customer is fired when the customer changes his/her Contact Information:
- https://prnt.sc/tefjlj
The remaining 2 events will be fired as you mentioned.
However, I can't reproduce your problem.

Please create a ticket to support your issue here:
- https://mageplaza.freshdesk.com/support/tickets/new

Thanks so much!

**Comment by icychocolate98** [comment]
Thanks you too!
