### ISSUE TITLE
Possibility to get tracking information in new_shipment webhook 

### ISSUE THREAD

**Issue by jason-newvision** [mageplaza/magento-2-webhook#58]
Hi there,

Is there any way of getting the tracking information (title / number) with the **New Shipment** webhook?

See screenshot for clarification of the field in question:
![image](https://user-images.githubusercontent.com/37378233/103379558-ebd89680-4add-11eb-991d-afab74fecca8.png)

Kind Regards
Jason

**Comment by Shinichi69** [comment]
Hi @jason-newvision 

I’m Shin from Mageplaza and I will support you on this issue.

I have customized it so that you can get the tracking information you mention with the New Shipment webhook.
Please download and replace this file to follow the path:
[Data.zip](https://github.com/mageplaza/magento-2-webhook/files/5756240/Data.zip)
- mageplaza/module-webhook/Helper/Data.php

Then use the following code in the hook to get this information:
{% for track in item.tracksCollection %}
       {{ track.title }}
       {{ track.track_number }}
{% endfor %}

Thanks so much!

**Comment by jason-newvision** [comment]
Hi @Shinichi69 

Thanks for coming back to me about this. This is very helpful and also gives me some idea on how to do other customisations if required.

Have a great new year!

Kind regards
Jason

**Comment by corpsysgit** [comment]
**I made the change in the code as it is in the Data.php that you sent @Shinichi69** 

          if ($item instanceof \Magento\Sales\Model\Order\Shipment) {
                $tracksCollection = $item->getTracksCollection()->getItems();
                $item->setData('tracksCollection', $tracksCollection);
            }

**But it still didn't work, with POST method:**

curl -H "Authorization: Token token=sfg999666t673t7t82" -H "Content-Type: application/json" -d '{
  "Nome": "{{ item.customer_firstname }} {{ item.customer_lastname }}",
  "Pedido": "{{ item.increment_id }}",
  "Status": "{{ item.status }}",
  "phoneNumber": "{{ item.shippingAddress.telephone }}",
  "phoneNumber2": "{{ item.billingAddress.telephone }}",
  "email": "{{ item.shippingAddress.email }}",
  "Cidade": "{{ item.shippingAddress.city }}",
  "Estado": "{{ item.shippingAddress.region }}",
  "tracking": "{% for track in item.tracksCollection %}{{ track.track_number }}{% endfor %}",
  "comments": "{{ item.customer_shipping_comments }}",
  "comments2": "{{ item.shipping_comments }}",
  "comments3": "{{ item.shipping_description }}"

}

' -X POST 'https://flows.messagebird.com/flows/f2efd5f4-ba6e-471c-a175-ed90983d6460/invoke'
