### ISSUE TITLE
{{ item.payment.po_number }} doesn't populate purchase order number. Receives blank

### ISSUE THREAD

**Issue by dmcmillin** [mageplaza/magento-2-webhook#89]
Anyone have a fix for this? I am using the offline sales method purchase order module that comes default by magento2. On CE. newest edition. 

all of my other fields are populating properly. Just not that one.

**Comment by phutx** [comment]
Hello @dmcmillin,

Many thanks for your interest and for using our Webhook module.
However, we cannot replicate the issue you are mentioning.
Please access the following link to submit a ticket so that we can assist you further in this matter:
https://mageplaza.freshdesk.com/support/tickets/new
Your help and understanding mean a lot to me.
Thank you is never enough.
